// SkillBridge — category taxonomy, thumbnail theming, and the original seed course data.
//
// The course catalog itself now lives in Firebase (courses/{id}), managed from admin.html,
// not here — that's what makes a real admin screen possible; a browser can edit a database,
// not a file on disk. Use loadCourses()/getCourseCached()/watchCourses() from app.js to read
// it. SEED_COURSES below is kept only as the one-time starter data admin.html imports into
// Firebase the first time the courses collection is empty; it's not read anywhere else.
//
// Lesson content: each lesson has a `content` field — the actual written lesson text shown
// on the course page. This was placeholder content standing in for real instructor material.
// A lesson can also carry an optional `videoUrl` (a YouTube/Vimeo embed URL) — if present,
// the video is shown above the text.

export const CATEGORIES = [
  "Tech & Coding",
  "Content Creation",
  "Design",
  "Career & Money",
  "Soft Skills",
];

// Stand-in for real cover photography: a gradient + icon per category, used to give every
// course a distinct-looking thumbnail without needing actual images. Swap a course's card
// or detail-page thumbnail for a real photo later by giving that course its own `thumbUrl`
// field and checking for it before falling back to this theme.
export const CATEGORY_THEME = {
  "Tech & Coding": { gradient: "linear-gradient(135deg, #14213D, #2B4C7E)", icon: "💻" },
  "Content Creation": { gradient: "linear-gradient(135deg, #C9821F, #E8A33D)", icon: "🎬" },
  "Design": { gradient: "linear-gradient(135deg, #5B3E63, #9B6B9E)", icon: "🎨" },
  "Career & Money": { gradient: "linear-gradient(135deg, #1F5C40, #2F7A57)", icon: "💼" },
  "Soft Skills": { gradient: "linear-gradient(135deg, #8C3420, #B3402A)", icon: "🗣️" },
};

// price is in naira; 0 means free.
export const SEED_COURSES = [
  {
    id: "c001",
    title: "Intro to Web Development",
    instructor: "Amaka O.",
    category: "Tech & Coding",
    price: 0,
    rating: 4.6,
    students: 1240,
    level: "Beginner",
    createdAt: "2026-02-10",
    description: "Learn how websites actually work. You'll go from a blank file to a live page you can share, using nothing but a browser and a text editor.",
    lessons: [
      { title: "How the web works", minutes: 12, content: "Every website you've ever visited comes down to three things: a browser asking for a file, a server sending one back, and HTML describing what's in it. We'll trace that journey step by step, from typing a URL to seeing a page render, so the rest of this course has something to hang on." },
      { title: "Your first HTML page", minutes: 18, content: "Open a plain text file, save it as index.html, and you've made a website. In this lesson you'll write your first page from scratch: the doctype, the head, the body, and enough tags to get real text and a heading on screen. Open it in your browser after every change — that instant feedback loop is the whole game." },
      { title: "Structuring content with tags", minutes: 22, content: "Headings, paragraphs, lists, links, and images cover most of what a page needs to say. We'll go through each one, plus why using the right tag for the job (a list for a list, not a pile of line breaks) matters for accessibility and for search engines reading your page later." },
      { title: "Adding style with CSS", minutes: 25, content: "HTML gives you structure; CSS gives you looks. You'll link a stylesheet to your page and control color, spacing, fonts, and layout with selectors and properties, turning the plain page from the last lesson into something that actually looks designed." },
      { title: "Publishing your page for free", minutes: 15, content: "A page sitting on your laptop isn't a website yet — it needs to live somewhere other people can reach. We'll deploy your page using a free static host so you walk away with a real, shareable link by the end of this lesson." },
    ],
  },
  {
    id: "c002",
    title: "HTML & CSS Basics",
    instructor: "Amaka O.",
    category: "Tech & Coding",
    price: 0,
    rating: 4.5,
    students: 980,
    level: "Beginner",
    createdAt: "2026-02-24",
    description: "A focused walk through the building blocks of every website: semantic HTML, the box model, flexbox, and responsive layouts.",
    lessons: [
      { title: "Semantic HTML", minutes: 16, content: "Tags like <header>, <nav>, <main>, and <article> describe what content is, not just how it looks. We'll rebuild a plain div-and-span page using semantic tags instead, and talk about why that choice helps screen readers, search engines, and future-you maintaining the code." },
      { title: "The box model", minutes: 20, content: "Every element on a page is a box with content, padding, a border, and a margin, in that order. Once this clicks, spacing stops feeling random — we'll use the browser's dev tools to actually see the box model around real elements and fix a couple of classic spacing bugs." },
      { title: "Flexbox layouts", minutes: 28, content: "Flexbox is how you line things up — a row of cards, a centered box, a navbar with space between links. You'll practice the core properties (display: flex, justify-content, align-items, gap) by building three common layouts from scratch." },
      { title: "Responsive design", minutes: 24, content: "A page that looks great on a laptop can be unusable on a phone. We'll use media queries to reflow a layout at different widths, and cover the handful of rules of thumb that keep a page readable from a small phone up to a wide desktop screen." },
    ],
  },
  {
    id: "c003",
    title: "Git & GitHub for Beginners",
    instructor: "Ngozi E.",
    category: "Tech & Coding",
    price: 0,
    rating: 4.4,
    students: 760,
    level: "Beginner",
    createdAt: "2026-03-05",
    description: "Stop emailing yourself zip files. Learn to track changes, undo mistakes, and collaborate with classmates using Git and GitHub.",
    lessons: [
      { title: "Why version control?", minutes: 10, content: "Before touching a single command, we'll look at the problem Git actually solves: knowing what changed, when, and being able to undo it. If you've ever renamed a file \"final_v3_ACTUAL.docx\", this lesson explains what you were missing." },
      { title: "Installing Git and your first commit", minutes: 20, content: "You'll install Git, set your name and email, turn a folder into a repository, and make your first commit. We'll go slowly through git status, git add, and git commit, since these three commands cover most of daily Git use." },
      { title: "Branches and merging", minutes: 24, content: "A branch lets you try something without touching the main version of your project. We'll create a branch, make changes on it, and merge it back in, including what to do when Git tells you there's a conflict." },
      { title: "Pushing to GitHub", minutes: 18, content: "Your commits live on your laptop until you push them somewhere. You'll connect a local repository to a GitHub repository and push your first project up, so it's backed up and shareable with a link." },
      { title: "Pull requests and collaboration", minutes: 22, content: "This is how real teams work together on code: open a pull request, get it reviewed, and merge it in. You'll open a practice pull request end to end and see what a review comment looks like from the other side." },
    ],
  },
  {
    id: "c004",
    title: "JavaScript Fundamentals",
    instructor: "Ngozi E.",
    category: "Tech & Coding",
    price: 9000,
    rating: 4.7,
    students: 640,
    level: "Beginner",
    createdAt: "2026-03-18",
    description: "Make your pages do things. Variables, functions, arrays, the DOM, and events, taught through small projects you build along the way.",
    lessons: [
      { title: "Variables and data types", minutes: 22, content: "let, const, strings, numbers, booleans, and the odd behavior of null and undefined. We'll cover how JavaScript stores and compares values, including a few gotchas (like why 0.1 + 0.2 isn't quite 0.3) that trip up almost everyone at first." },
      { title: "Functions and scope", minutes: 26, content: "Functions are how you package up logic to reuse it. You'll write functions with parameters and return values, then dig into scope — why a variable declared inside a function doesn't exist outside it, and why that's usually a good thing." },
      { title: "Arrays and objects", minutes: 30, content: "Arrays hold ordered lists, objects hold labeled data — together they model almost everything in a real app. We'll practice the array methods you'll use constantly (map, filter, find) and how to read and update nested object data." },
      { title: "Working with the DOM", minutes: 34, content: "The DOM is JavaScript's live view of the page. You'll select elements, read and change their text and attributes, and add or remove elements entirely, turning a static page into one that reacts." },
      { title: "Events and interactivity", minutes: 28, content: "Clicks, key presses, form submissions — events are how a page listens for what a user does. We'll attach event listeners and use them to build small interactions, the same pattern used in every button and form you've ever clicked." },
      { title: "Project: a to-do app", minutes: 45, content: "Everything from this course comes together here: you'll build a working to-do list — add items, check them off, delete them, keep them in an array — entirely with what you've already learned. This is the project to put in your portfolio." },
    ],
  },
  {
    id: "c005",
    title: "Video Editing with CapCut",
    instructor: "Hikmat K.",
    category: "Content Creation",
    price: 8000,
    rating: 4.9,
    students: 1510,
    level: "Beginner",
    createdAt: "2026-01-20",
    description: "Edit videos on your phone that look like they came from a studio. Cuts, captions, transitions, sound design, and export settings that work for every platform.",
    lessons: [
      { title: "CapCut interface tour", minutes: 14, content: "Before editing anything, get comfortable with where things live: the timeline, the clip panel, the export button, and the tools you'll reach for most. A five-minute orientation now saves a lot of hunting-around-in-menus later." },
      { title: "Cutting and trimming clips", minutes: 20, content: "Good editing is mostly good cutting. You'll learn to trim dead space, split clips at the right beat, and pace a sequence so it never drags — the single skill that improves a video more than any effect." },
      { title: "Auto captions and text styles", minutes: 18, content: "Most viewers watch with the sound off, so captions aren't optional anymore. We'll generate auto-captions, clean up the inevitable mistakes, and style text so it's readable and on-brand." },
      { title: "Transitions and effects", minutes: 22, content: "Used well, transitions are invisible; used badly, they scream \"amateur\". We'll cover the handful of transitions worth knowing and, more importantly, when to use no transition at all." },
      { title: "Sound, music and voiceover", minutes: 20, content: "Bad audio kills a good video faster than bad footage does. You'll balance voiceover against background music, clean up rough audio, and pick music that fits the pace of your edit without drowning out speech." },
      { title: "Exporting for TikTok, Reels and YouTube", minutes: 12, content: "Each platform wants a different aspect ratio, resolution, and length. We'll go through export settings for TikTok, Reels, and YouTube Shorts so your video looks sharp wherever it's posted." },
    ],
  },
  {
    id: "c006",
    title: "Content Creation with Your Phone",
    instructor: "Hikmat K.",
    category: "Content Creation",
    price: 0,
    rating: 4.6,
    students: 2030,
    level: "Beginner",
    createdAt: "2026-01-08",
    description: "No camera, no ring light, no problem. Learn framing, lighting and sound with just your phone and the light from your window.",
    lessons: [
      { title: "Finding good light anywhere", minutes: 15, content: "The single biggest difference between amateur and professional-looking footage is light, not the camera. You'll learn to use a window as a free softbox and spot the harsh overhead lighting that makes every shot look worse." },
      { title: "Framing and composition", minutes: 18, content: "Where you put the subject in the frame changes how a shot feels. We'll cover the rule of thirds, eye-line, and headroom — simple rules that make any phone shot look intentional instead of accidental." },
      { title: "Recording clean audio", minutes: 16, content: "Viewers forgive shaky footage far more than they forgive bad audio. You'll learn phone mic placement, how to avoid wind and echo, and a couple of cheap accessories that fix most audio problems." },
      { title: "Planning a week of content", minutes: 20, content: "Consistency beats sporadic bursts of posting. We'll build a simple weekly content plan so you're never staring at your phone wondering what to film next." },
    ],
  },
  {
    id: "c007",
    title: "Growing on TikTok & Instagram",
    instructor: "Ada M.",
    category: "Content Creation",
    price: 6000,
    rating: 4.5,
    students: 890,
    level: "Intermediate",
    createdAt: "2026-04-02",
    description: "How the algorithms actually reward content, how to find your niche, and how to turn views into a community that sticks around.",
    lessons: [
      { title: "How the feed decides what to show", minutes: 18, content: "The algorithm isn't magic — it's tracking a handful of signals like watch time and shares, then showing more of what works. We'll break down what actually moves those signals so you stop guessing." },
      { title: "Finding your niche", minutes: 20, content: "Trying to appeal to everyone usually means reaching no one. You'll narrow down to a specific niche and audience, the thing that makes an algorithm confident enough to push your content further." },
      { title: "Hooks: the first three seconds", minutes: 16, content: "Most viewers decide whether to keep watching in the first three seconds. We'll go through hook formulas that actually hold attention, and why your best line usually belongs at the start, not the end." },
      { title: "Posting cadence and analytics", minutes: 22, content: "You'll learn to read your own analytics — watch time, retention graphs, follower growth — and use them to decide what to post more of, instead of guessing from vibes." },
      { title: "Collaborations and brand deals", minutes: 24, content: "Once you have an audience, brands and other creators come calling. We'll cover how to price a brand deal, what to put in a simple agreement, and how to collaborate without it feeling like an ad." },
    ],
  },
  {
    id: "c008",
    title: "Canva for Creators",
    instructor: "Zainab I.",
    category: "Design",
    price: 5000,
    rating: 4.7,
    students: 1120,
    level: "Beginner",
    createdAt: "2026-02-15",
    description: "Design flyers, slides, and social posts that look professional. Learn the Canva tools that matter and the design rules behind them.",
    lessons: [
      { title: "Canva workspace essentials", minutes: 14, content: "A fast tour of Canva's layout — templates, elements, uploads, and the tools you'll use in every design, so you're not hunting through menus mid-project." },
      { title: "Typography that reads well", minutes: 20, content: "Two fonts, clear hierarchy, and enough contrast — that's most of good typography. We'll cover font pairing and sizing rules that instantly make a design look more considered." },
      { title: "Colour and contrast", minutes: 18, content: "Color choices aren't just taste — some combinations are genuinely hard to read. You'll learn a simple approach to picking a palette and checking contrast so your text stays legible." },
      { title: "Templates: use them without looking like you did", minutes: 22, content: "Templates are a great starting point, not a finish line. We'll take a generic template and customize it enough that it looks like your own design, not a copy-paste job." },
      { title: "Brand kits and batch designing", minutes: 20, content: "If you're designing for the same client or brand repeatedly, a brand kit saves hours. You'll set one up and use it to batch out a week's worth of consistent social posts quickly." },
    ],
  },
  {
    id: "c009",
    title: "UI Design Fundamentals in Figma",
    instructor: "Zainab I.",
    category: "Design",
    price: 10000,
    rating: 4.8,
    students: 530,
    level: "Intermediate",
    createdAt: "2026-04-20",
    description: "Design real app screens in Figma. Layout grids, components, auto layout, and a full mobile app mock-up for your portfolio.",
    lessons: [
      { title: "Figma setup and frames", minutes: 18, content: "You'll get comfortable with Figma's frames, pages, and panels, and set up your first mobile-screen frame at the right dimensions to start designing." },
      { title: "Grids, spacing and hierarchy", minutes: 24, content: "A consistent spacing system is what separates a design that looks 'designed' from one that looks thrown together. We'll set up a grid and spacing scale and use it to lay out a real screen." },
      { title: "Components and variants", minutes: 30, content: "Instead of redrawing the same button forty times, you'll build it once as a component with variants (default, hover, disabled), the same way production design systems work." },
      { title: "Auto layout", minutes: 28, content: "Auto layout makes elements resize and reflow automatically, the same way a real coded interface would. You'll rebuild a static layout using auto layout so it holds together as content changes." },
      { title: "Prototyping interactions", minutes: 26, content: "A static mock-up doesn't show how a screen actually feels to use. You'll wire up clickable prototypes between screens so reviewers can tap through your design like a real app." },
      { title: "Project: a mobile app onboarding flow", minutes: 50, content: "You'll design a complete three-screen onboarding flow for a mobile app, using the components, grid, and auto layout skills from this course — a strong, portfolio-ready piece by the end." },
    ],
  },
  {
    id: "c010",
    title: "Intro to Graphic Design",
    instructor: "Femi B.",
    category: "Design",
    price: 0,
    rating: 4.3,
    students: 1450,
    level: "Beginner",
    createdAt: "2026-01-28",
    description: "The principles behind every good design: alignment, contrast, repetition, proximity. Learn to see design before you make it.",
    lessons: [
      { title: "What makes a design good?", minutes: 14, content: "Before tools or software, this lesson is about training your eye — looking at a design and being able to say specifically what's working and what isn't, instead of just \"I like it\" or \"something's off\"." },
      { title: "The four principles", minutes: 22, content: "Alignment, contrast, repetition, and proximity explain almost every design decision you'll ever make. We'll go through each with clear before-and-after examples so you can spot them anywhere." },
      { title: "Choosing and pairing fonts", minutes: 20, content: "Two well-chosen fonts will take you further than ten mediocre ones. You'll learn a simple, reliable approach to pairing a heading font with a body font." },
      { title: "Critiquing your own work", minutes: 16, content: "The fastest way to improve is being able to critique your own work honestly. We'll walk through a simple checklist to run any design past before calling it finished." },
    ],
  },
  {
    id: "c011",
    title: "Scholarship Application Prep",
    instructor: "Tolu A.",
    category: "Career & Money",
    price: 0,
    rating: 4.8,
    students: 1870,
    level: "Beginner",
    createdAt: "2026-03-01",
    description: "Where to find scholarships, how to write a personal statement that stands out, and how to get strong recommendation letters without awkwardness.",
    lessons: [
      { title: "Finding scholarships you actually qualify for", minutes: 18, content: "There are more scholarships out there than most students realize — most just never find out about them. We'll cover where to search and how to quickly tell which ones are worth your time to apply to." },
      { title: "Writing the personal statement", minutes: 30, content: "This is usually the part that decides the outcome. You'll learn a structure for telling a specific, honest story about yourself instead of a generic list of achievements that sounds like everyone else's." },
      { title: "Asking for recommendation letters", minutes: 14, content: "Asking for a letter feels awkward, but there's a right way to do it that makes it easy for the person writing it. We'll cover who to ask, how to ask, and what to give them to make the letter strong." },
      { title: "Interviews and follow-up", minutes: 20, content: "If you make it to an interview, preparation matters more than charisma. We'll go through common scholarship interview questions and how to follow up afterward without being pushy." },
    ],
  },
  {
    id: "c012",
    title: "Freelancing 101: Getting Your First Client",
    instructor: "Tolu A.",
    category: "Career & Money",
    price: 7000,
    rating: 4.7,
    students: 710,
    level: "Beginner",
    createdAt: "2026-04-11",
    description: "Turn a skill into income. Pricing, portfolios, pitching, contracts, and getting paid reliably as a student freelancer.",
    lessons: [
      { title: "Picking a service you can sell", minutes: 16, content: "Not every skill is equally easy to sell right away. We'll help you pick a specific, sellable service to start with, based on what you already know how to do." },
      { title: "Building a one-page portfolio", minutes: 24, content: "You don't need ten projects to start — you need one page that shows your best two or three clearly. We'll put one together, even if you're starting with zero paid clients so far." },
      { title: "Pricing without underselling yourself", minutes: 20, content: "Most beginners price too low out of fear, then resent the work. You'll learn a simple way to set a starting price that's fair to you and reasonable for a first-time client." },
      { title: "Pitching and following up", minutes: 22, content: "A pitch that gets ignored usually isn't about your skill — it's about the message. We'll write a pitch template you can adapt, plus how to follow up without sounding desperate." },
      { title: "Simple contracts and getting paid", minutes: 18, content: "A one-page agreement protects both you and the client. You'll get a simple contract template and learn how to structure payment so you're not left chasing money after the work is done." },
    ],
  },
  {
    id: "c013",
    title: "Personal Finance for Students",
    instructor: "Kemi S.",
    category: "Career & Money",
    price: 3500,
    rating: 4.6,
    students: 1290,
    level: "Beginner",
    createdAt: "2026-02-05",
    description: "Budgeting on an allowance, saving small amounts consistently, avoiding debt traps, and the basics of investing when you're ready.",
    lessons: [
      { title: "A budget that survives the month", minutes: 18, content: "Most budgets fail because they're too strict to actually follow. We'll build a simple, realistic budget around an allowance or irregular income that you'll actually stick to." },
      { title: "Saving when money is tight", minutes: 16, content: "Saving doesn't require a big income — it requires a system. You'll set up a small, automatic saving habit that works even on very little money." },
      { title: "Loans, credit and traps to avoid", minutes: 20, content: "Easy credit can look like free money until the terms catch up with you. We'll cover how to read the real cost of a loan and the warning signs of predatory lending." },
      { title: "Investing basics", minutes: 22, content: "You don't need to be rich to start investing, just consistent. We'll cover the basic concepts — compound growth, risk, and getting started small — without the jargon." },
    ],
  },
  {
    id: "c014",
    title: "CV & LinkedIn That Get Interviews",
    instructor: "Chuka N.",
    category: "Career & Money",
    price: 4000,
    rating: 4.5,
    students: 960,
    level: "Beginner",
    createdAt: "2026-03-22",
    description: "Write a CV that gets past screening, build a LinkedIn profile recruiters actually message, and apply in a way that gets responses.",
    lessons: [
      { title: "What recruiters look for in 6 seconds", minutes: 14, content: "Recruiters skim, they don't read, at least at first. We'll cover exactly what they scan for in those first few seconds so your CV survives the skim." },
      { title: "Writing your CV", minutes: 26, content: "You'll rewrite your experience using results, not just duties — the difference between \"managed social media\" and \"grew followers by 40% in three months\", and why that difference gets interviews." },
      { title: "A LinkedIn profile that gets found", minutes: 22, content: "A weak LinkedIn profile means recruiters searching your field never find you. We'll optimize your headline, About section, and keywords so you show up in the right searches." },
      { title: "Applying and following up", minutes: 16, content: "How you apply matters almost as much as what you apply with. We'll cover how to tailor applications quickly and when a polite follow-up actually helps instead of annoying." },
    ],
  },
  {
    id: "c015",
    title: "Public Speaking with Confidence",
    instructor: "Ada M.",
    category: "Soft Skills",
    price: 5000,
    rating: 4.6,
    students: 820,
    level: "Beginner",
    createdAt: "2026-03-12",
    description: "Speak clearly in class presentations, interviews, and on camera. Practical drills for nerves, structure, and presence.",
    lessons: [
      { title: "Dealing with nerves", minutes: 16, content: "Nerves don't fully go away, and that's fine — the goal is managing them, not eliminating them. We'll cover breathing and preparation techniques that keep nerves from taking over mid-talk." },
      { title: "Structuring a talk", minutes: 20, content: "A talk with a clear structure is far easier to deliver and far easier to follow. You'll learn a simple opening-middle-close structure you can drop almost any topic into." },
      { title: "Voice, pace and pauses", minutes: 18, content: "How you say something affects how it lands as much as what you say. We'll practice slowing down, using pauses on purpose, and projecting without shouting." },
      { title: "Handling questions", minutes: 14, content: "Unscripted questions are where most speakers panic. We'll cover a simple method for buying yourself thinking time and answering honestly, even when you don't fully know the answer." },
    ],
  },
  {
    id: "c016",
    title: "Acing Your IT Defense Presentation",
    instructor: "Chuka N.",
    category: "Soft Skills",
    price: 5500,
    rating: 4.9,
    students: 1030,
    level: "Intermediate",
    createdAt: "2026-04-25",
    description: "Everything you need to defend your industrial training report: slide design, what panels ask, and how to answer questions you don't know.",
    lessons: [
      { title: "What the panel is really assessing", minutes: 15, content: "Panels usually care less about a perfect answer and more about whether you understand your own work. We'll cover what's actually being evaluated so you can prepare for the right thing." },
      { title: "Slides that support you, not replace you", minutes: 22, content: "Dense slides make a panel read instead of listen. You'll rebuild a cluttered slide deck into one that supports your talking instead of competing with it." },
      { title: "Rehearsing the 10-minute version", minutes: 18, content: "You'll practice compressing your full report into a tight ten-minute version, the length most defense presentations are actually given." },
      { title: "Answering hard questions", minutes: 20, content: "We'll go through common panel questions and, more importantly, a method for handling the ones you genuinely don't know the answer to without freezing up." },
      { title: "Dress, posture and delivery", minutes: 12, content: "Small things — posture, eye contact, how you stand — shape a panel's first impression before you've said a word. We'll cover the basics that make you look prepared and confident." },
    ],
  },
];

export const courseDuration = (c) => c.lessons.reduce((sum, l) => sum + l.minutes, 0);
